[tool.poetry]
name = "cashu"
version = "0.0.1"
description = "Ecash wallet and mint."
authors = ["calle <callebtc@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pycrypto = "^2.6.1"
ecc = "0.0.1"
requests = "2.27.1"
pytest-asyncio = "0.19.0"
SQLAlchemy = "1.3.24"
sqlalchemy-aio = "0.17.0"
certifi = "2021.10.8"
charset-normalizer = "2.0.12"
click = "8.0.4"
Flask = "2.2.2"
idna = "3.3"
itsdangerous = "2.1.1"
Jinja2 = "3.0.3"
MarkupSafe = "2.1.1"
urllib3 = "1.26.9"
Werkzeug = "2.2.2"
ecc-pycrypto = {git = "https://github.com/lc6chang/ecc-pycrypto.git", rev = "v1.0.1"}
psycopg2 = "^2.9.3"
asgiref = "^3.5.2"
pydantic = "^1.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
